name = "CrookedTwistedFunctions"
uuid = "335fe7f5-1efd-45d2-9984-8ab936cfeaa1"
authors = ["Pierre Abbat <phma@bezitopo.org>", "Hitokiri Battosai <battosai@dnmx.cc>"]
version = "0.1.0"

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
CairoMakie = "0.15.6"
OffsetArrays = "1.17.0"
StatsBase = "0.34.6"
